import type { Metadata } from "next";
import "./globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { Plus_Jakarta_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/themes/theme-provider";
import { locales } from "@/i18n/config";
// import ThemeDataProvider from "@/themes/context/theme-data-context";

const font = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
  params: any; // Adjust type as needed, e.g., { locale: string }
};

export default async function RootLayout({
  children, params
}: Readonly<RootLayoutProps>) {
  const { locale } = params;
  if (!hasLocale(locales, locale)) {
    notFound();
  } 
  return (
    <html lang={locale} >
      <body
        className={`${font.variable} bg-white dark:bg-dark-300 font-sans antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider>
          {/* <ThemeDataProvider> */}
            {/* <Navbar /> */}
            {children}
          {/* </ThemeDataProvider> */}
          </NextIntlClientProvider>

        </ThemeProvider>
      </body>
    </html>
  );
}
